# Site settings
title: Glenn Dayton
description: Full Stack Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Glenn Dayton
user_description: no
user_title: Software Engineer
email: glenn.dayton24@gmail.com
twitter_username: glenndayton
github_username: gdayton
gplus_username: glenndayton

# Google-analytics
google-analytics:
  id: "UA-28176214-3"

exclude: ['package.json', 'src' , 'node_modules']

github: [metadata]
url: gdayton.github.io
baseurl: /